/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2023-03-09 19:24:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Login | By Code Info</title>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    body {\r\n");
      out.write("  background-color: #344a72;\r\n");
      out.write("  font-family: \"Roboto\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup-box {\r\n");
      out.write("  width: 360px;\r\n");
      out.write("  height: 620px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box {\r\n");
      out.write("  width: 360px;\r\n");
      out.write("  height: 280px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("  margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form label {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form input {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 7px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border: 1px solid gray;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"button\"] {\r\n");
      out.write("  width: 320px;\r\n");
      out.write("  height: 35px;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background-color: #49c1a2;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("p {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding-top: 20px;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".para-2 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  margin-top: -10px;\r\n");
      out.write("}\r\n");
      out.write(".para-2 a {\r\n");
      out.write("  color: #49c1a2;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"login-box\">\r\n");
      out.write("      <h1>Login</h1>\r\n");
      out.write("      <form>\r\n");
      out.write("        <label>Email</label>\r\n");
      out.write("        <input type=\"email\" placeholder=\"\" />\r\n");
      out.write("        <label>Password</label>\r\n");
      out.write("        <input type=\"password\" placeholder=\"\" />\r\n");
      out.write("        <input type=\"button\" value=\"Submit\" />\r\n");
      out.write("      <closeform></closeform></form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <p class=\"para-2\">\r\n");
      out.write("      Not have an account? <a href=\"test\">Sign Up Here</a>\r\n");
      out.write("    </p>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
